makepkg: add basic support for alternatives
Alternatives are specified in makepkg via (e.g.):

alternative=('sh')

There should be a file (e.g.) sh.alternative alongside the PKGBUILD containing
a list of symlinks to be created with the alternative is active.  This file is
stored in the root of the package as (e.g.) .ALTERNATIVE.sh.

Signed-off-by: Allan McRae <allan@archlinux.org>

diff --git a/scripts/makepkg.sh.in b/scripts/makepkg.sh.in
--- a/scripts/makepkg.sh.in
+++ b/scripts/makepkg.sh.in
@@ -710,6 +710,16 @@ create_package() {
 		fi
 	done
 
+	# check for alternative files
+	for i in ${alternative[@]}; do
+		msg2 "$(gettext "Adding %s file...")" "$i.alternative"
+		if ! cp "$startdir/$i.alternative" ".ALTERNATIVE.$i"; then
+			error "$(gettext "Failed to add %s file to package.")" "$i.alternative"
+			exit $E_MISSING_FILE
+		fi
+		chmod 644 ".ALTERNATIVE.$i"
+	done
+
 	# tar it up
 	local fullver=$(get_full_version)
 	local pkg_file="$PKGDEST/${pkgname}-${fullver}-${pkgarch}${PKGEXT}"
